fix check_auth filename

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -12,7 +12,7 @@ permissions:
   contents: read
 jobs:
   refresh-auth:
-    uses: ./.github/workflows/refresh_auth.yml
+    uses: ./.github/workflows/check_auth.yml
     secrets: inherit
   test-templates:
     runs-on: ubuntu-latest
@@ -38,8 +38,8 @@ jobs:
           npm install https://github.com/silverfin/silverfin-cli.git
           VERSION=$(./node_modules/silverfin-cli/bin/cli.js -V)
           echo "CLI version: ${VERSION}"
-      - name: Get changed files in the reconciliation_texts folder
-        id: changed-files-reconciliations
+      - name: Get changed files
+        id: changed-files
         uses: tj-actions/changed-files@v35
         with:
           since_last_remote_commit: false
@@ -62,7 +62,7 @@ jobs:
           for name in "${changed_templates[@]}"; do
             echo "$name"
           done
-      - name: Run liquid tests for updated reconciliations
+      - name: Run liquid tests for updated templates
         run: |
           declare -a ERRORS
           for CURRENT_DIR in ${{ steps.templates_changed.outputs.changed_templates }}; do
@@ -102,61 +102,61 @@ jobs:
               echo "Errors: ${ERRORS[@]}, please run the tests locally to fix the errors"
               exit 1
           fi
-      - name: Get changed files in the shared_parts folder
-        id: changed-files-shared-parts
-        uses: tj-actions/changed-files@v35
-        with:
-          since_last_remote_commit: false
-          dir_names: true
-          files: "shared_parts"
-      - name: List all changed files in the shared_parts folder
-        run: |
-          for file in ${{ steps.changed-files-shared-parts.outputs.all_changed_files }}; do
-            echo "$file was changed"
-          done
-      - name: Run liquid tests for reconciliations that use updated shared parts
-        run: |
-          declare -a ERRORS
-          for CURRENT_DIR in ${{ steps.changed-files-shared-parts.outputs.all_changed_files }}; do
-            echo "Checking ${CURRENT_DIR}"
-            while [[ "${CURRENT_DIR}" != "." ]]; do
-              if [[ -e "${CURRENT_DIR}/config.json" ]]; then
-                JSON=$(cat ${CURRENT_DIR}/config.json)
-                HANDLES=$(echo "$JSON" | jq -r '.used_in[].handle')
-                # LOOP THROUGH EACH RECONCILIATION
-                for HANDLE in $HANDLES; do
-                  # CHECK IF RECONCILIATION CONFIG IS IMPORTED
-                  if [[ -f "./reconciliation_texts/${HANDLE}/config.json" ]]; then
-                    # RUN THE TEST FOR THE FIRST FIRM ID IN THE RECONCILIATION CONFIG
-                    FIRM_ID=$(cat ./reconciliation_texts/${HANDLE}/config.json | jq -r ".id" | jq "keys_unsorted" | jq "first" | tr -d '"')
-                    # RUN TEST
-                    echo "Running tests for ${HANDLE} in firm ${FIRM_ID}"
-                    FORMATTED_OUTPUT=$(node ./node_modules/silverfin-cli/bin/cli.js run-test --handle "${HANDLE}" --firm "${FIRM_ID}")
-                    OUTPUT=$(node ./node_modules/silverfin-cli/bin/cli.js run-test --handle "${HANDLE}" --firm "${FIRM_ID}" --status 2>&1)
-                    # CHECK OUTPUT
-                    if [[ "$OUTPUT" =~ "PASSED" ]]; then
-                      echo "${HANDLE}: passed"
-                    elif [[ "$OUTPUT" =~ "FAILED" ]]; then
-                      echo "${HANDLE}: failed"
-                      echo "Details of test run: ${FORMATTED_OUTPUT}"
-                      ERRORS+=("${HANDLE}")
-                    else
-                      echo "${HANDLE}: other errors: ${OUTPUT}"
-                      ERRORS+=("${OUTPUT}")
-                    fi
-                  fi
-                done
-                break
-              else
-                echo "Config file not found in ${CURRENT_DIR}"
-                CURRENT_DIR="$(dirname "${CURRENT_DIR}")"
-              fi
-            done
-          done
-          # CHECK ERRORS PRESENT
-          if [ ${#ERRORS[@]} -eq 0 ]; then
-              echo "All tests have passed"
-          else
-              echo "Errors: ${ERRORS[@]}, please run the tests locally to fix the errors"
-              exit 1
-          fi
+      # - name: Get changed files in the shared_parts folder
+      #   id: changed-files-shared-parts
+      #   uses: tj-actions/changed-files@v35
+      #   with:
+      #     since_last_remote_commit: false
+      #     dir_names: true
+      #     files: "shared_parts"
+      # - name: List all changed files in the shared_parts folder
+      #   run: |
+      #     for file in ${{ steps.changed-files-shared-parts.outputs.all_changed_files }}; do
+      #       echo "$file was changed"
+      #     done
+      # - name: Run liquid tests for reconciliations that use updated shared parts
+      #   run: |
+      #     declare -a ERRORS
+      #     for CURRENT_DIR in ${{ steps.changed-files-shared-parts.outputs.all_changed_files }}; do
+      #       echo "Checking ${CURRENT_DIR}"
+      #       while [[ "${CURRENT_DIR}" != "." ]]; do
+      #         if [[ -e "${CURRENT_DIR}/config.json" ]]; then
+      #           JSON=$(cat ${CURRENT_DIR}/config.json)
+      #           HANDLES=$(echo "$JSON" | jq -r '.used_in[].handle')
+      #           # LOOP THROUGH EACH RECONCILIATION
+      #           for HANDLE in $HANDLES; do
+      #             # CHECK IF RECONCILIATION CONFIG IS IMPORTED
+      #             if [[ -f "./reconciliation_texts/${HANDLE}/config.json" ]]; then
+      #               # RUN THE TEST FOR THE FIRST FIRM ID IN THE RECONCILIATION CONFIG
+      #               FIRM_ID=$(cat ./reconciliation_texts/${HANDLE}/config.json | jq -r ".id" | jq "keys_unsorted" | jq "first" | tr -d '"')
+      #               # RUN TEST
+      #               echo "Running tests for ${HANDLE} in firm ${FIRM_ID}"
+      #               FORMATTED_OUTPUT=$(node ./node_modules/silverfin-cli/bin/cli.js run-test --handle "${HANDLE}" --firm "${FIRM_ID}")
+      #               OUTPUT=$(node ./node_modules/silverfin-cli/bin/cli.js run-test --handle "${HANDLE}" --firm "${FIRM_ID}" --status 2>&1)
+      #               # CHECK OUTPUT
+      #               if [[ "$OUTPUT" =~ "PASSED" ]]; then
+      #                 echo "${HANDLE}: passed"
+      #               elif [[ "$OUTPUT" =~ "FAILED" ]]; then
+      #                 echo "${HANDLE}: failed"
+      #                 echo "Details of test run: ${FORMATTED_OUTPUT}"
+      #                 ERRORS+=("${HANDLE}")
+      #               else
+      #                 echo "${HANDLE}: other errors: ${OUTPUT}"
+      #                 ERRORS+=("${OUTPUT}")
+      #               fi
+      #             fi
+      #           done
+      #           break
+      #         else
+      #           echo "Config file not found in ${CURRENT_DIR}"
+      #           CURRENT_DIR="$(dirname "${CURRENT_DIR}")"
+      #         fi
+      #       done
+      #     done
+      #     # CHECK ERRORS PRESENT
+      #     if [ ${#ERRORS[@]} -eq 0 ]; then
+      #         echo "All tests have passed"
+      #     else
+      #         echo "Errors: ${ERRORS[@]}, please run the tests locally to fix the errors"
+      #         exit 1
+      #     fi
